# Generated by Django 5.2 on 2025-06-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
            ],
            options={
                'verbose_name': 'repuesto de reparación',
                'verbose_name_plural': 'repuestos de reparación',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('notificado_cliente', models.BooleanField(default=False, verbose_name='notificado al cliente')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de notificación')),
                ('metodo_notificacion', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20, verbose_name='método de notificación')),
            ],
            options={
                'verbose_name': 'seguimiento de reparación',
                'verbose_name_plural': 'seguimientos de reparación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ServicioReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('instalacion', 'Instalación'), ('configuracion', 'Configuración'), ('otro', 'Otro')], default='reparacion', max_length=15, verbose_name='tipo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('tiempo_estimado', models.PositiveIntegerField(default=1, verbose_name='tiempo estimado (horas)')),
                ('requiere_diagnostico_previo', models.BooleanField(default=False, verbose_name='requiere diagnóstico previo')),
                ('disponible_online', models.BooleanField(default=True, verbose_name='disponible online')),
            ],
            options={
                'verbose_name': 'servicio de reparación',
                'verbose_name_plural': 'servicios de reparación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CitaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('tipo_equipo', models.CharField(max_length=100, verbose_name='tipo de equipo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='clientes.cliente', verbose_name='cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'cita de servicio',
                'verbose_name_plural': 'citas de servicio',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='GarantiaReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('condiciones', models.TextField(verbose_name='condiciones')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'garantía de reparación',
                'verbose_name_plural': 'garantías de reparación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('tipo_equipo', models.CharField(max_length=50, verbose_name='tipo de equipo')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='modelo')),
                ('problema_reportado', models.TextField(verbose_name='problema reportado')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En Diagnóstico'), ('reparacion', 'En Reparación'), ('finalizado', 'Finalizado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20, verbose_name='estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='prioridad')),
                ('costo_diagnostico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo diagnóstico')),
                ('costo_reparacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo reparación')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo repuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('facturado', models.BooleanField(default=False, verbose_name='facturado')),
                ('public_url', models.URLField(blank=True, unique=True, verbose_name='URL pública')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha recepción')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='fecha estimada entrega')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='fecha entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='clientes.cliente', verbose_name='cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'reparación',
                'verbose_name_plural': 'reparaciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
