# Generated by Django 5.2 on 2025-05-29 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
            ],
            options={
                'verbose_name': 'repuesto de reparación',
                'verbose_name_plural': 'repuestos de reparación',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='estado nuevo')),
                ('comentario', models.TextField(verbose_name='comentario')),
                ('notificado_cliente', models.BooleanField(default=False, verbose_name='notificado al cliente')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de notificación')),
            ],
            options={
                'verbose_name': 'seguimiento de reparación',
                'verbose_name_plural': 'seguimientos de reparación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ServicioReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('instalacion', 'Instalación'), ('configuracion', 'Configuración'), ('otro', 'Otro')], default='reparacion', max_length=15, verbose_name='tipo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('tiempo_estimado', models.PositiveIntegerField(default=1, verbose_name='tiempo estimado (horas)')),
                ('requiere_diagnostico_previo', models.BooleanField(default=False, verbose_name='requiere diagnóstico previo')),
                ('disponible_online', models.BooleanField(default=True, verbose_name='disponible online')),
            ],
            options={
                'verbose_name': 'servicio de reparación',
                'verbose_name_plural': 'servicios de reparación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de recepción')),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True, verbose_name='fecha estimada de entrega')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('tipo_equipo', models.CharField(max_length=100, verbose_name='tipo de equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='número de serie')),
                ('accesorios', models.TextField(blank=True, verbose_name='accesorios')),
                ('problema_reportado', models.TextField(verbose_name='problema reportado')),
                ('diagnostico', models.TextField(blank=True, verbose_name='diagnóstico')),
                ('solucion', models.TextField(blank=True, verbose_name='solución')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En diagnóstico'), ('espera_repuestos', 'Esperando repuestos'), ('en_reparacion', 'En reparación'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('no_reparable', 'No reparable'), ('cancelado', 'Cancelado')], default='recibido', max_length=20, verbose_name='estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='prioridad')),
                ('costo_diagnostico', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de diagnóstico')),
                ('costo_reparacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de reparación')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de repuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('facturado', models.BooleanField(default=False, verbose_name='facturado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='clientes.cliente', verbose_name='cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'reparación',
                'verbose_name_plural': 'reparaciones',
                'ordering': ['-fecha_recepcion'],
            },
        ),
    ]
