# Generated by Django 5.2 on 2025-06-09 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('reparaciones', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='ventas.venta', verbose_name='factura'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='técnico'),
        ),
        migrations.AddField(
            model_name='garantiareparacion',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='reparaciones.reparacion', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='citaservicio',
            name='reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='reparaciones.reparacion', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='repuestoreparacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='repuestoreparacion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='repuestoreparacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reparaciones', to='inventario.producto', verbose_name='producto'),
        ),
        migrations.AddField(
            model_name='repuestoreparacion',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='reparaciones.reparacion', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='seguimientoreparacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='seguimientoreparacion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='seguimientoreparacion',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='reparaciones.reparacion', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='servicioreparacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='servicioreparacion',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='servicioreparacion',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_reparacion', to='inventario.producto', verbose_name='producto asociado'),
        ),
        migrations.AddField(
            model_name='servicioreparacion',
            name='reparaciones',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='reparaciones.reparacion', verbose_name='reparaciones'),
        ),
    ]
