# Generated by Django 5.2 on 2025-06-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestoreparacion',
            name='impuesto_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='impuesto unitario'),
        ),
    ]
