# Generated by Django 5.2 on 2025-06-17 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0003_repuestoreparacion_impuesto_unitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('completado', models.BooleanField(default=False, verbose_name='completado')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='fecha completado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_servicio', to='reparaciones.reparacion', verbose_name='reparación')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='reparaciones.servicioreparacion', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'detalle de servicio',
                'verbose_name_plural': 'detalles de servicio',
                'ordering': ['id'],
                'unique_together': {('reparacion', 'servicio')},
            },
        ),
    ]
