# Generated by Django 5.2 on 2025-06-17 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('reparaciones', '0004_add_detalle_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioreparacion',
            name='producto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicio_reparacion', to='inventario.producto', verbose_name='producto asociado'),
        ),
    ]
