# Generated by Django 5.2 on 2025-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0005_make_producto_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='public_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL pública'),
        ),
    ]
