# Generated by Django 5.2 on 2025-06-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0006_modify_public_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='diagnóstico'),
        ),
    ]
