# Generated by Django 5.2 on 2025-06-10 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('venta', 'Venta'), ('compra', 'Compra'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre')], default='manual', max_length=10, verbose_name='tipo')),
                ('concepto', models.CharField(max_length=200, verbose_name='concepto')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('validado', 'Validado'), ('anulado', 'Anulado')], default='borrador', max_length=10, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de referencia')),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, verbose_name='tipo de referencia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'asiento contable',
                'verbose_name_plural': 'asientos contables',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número')),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito'), ('retencion', 'Retención'), ('liquidacion', 'Liquidación de Compra')], max_length=15, verbose_name='tipo')),
                ('fecha_emision', models.DateField(verbose_name='fecha de emisión')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA y otros impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitido', 'Emitido'), ('anulado', 'Anulado')], default='borrador', max_length=10, verbose_name='estado')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='fiscal.asientocontable', verbose_name='asiento contable')),
                ('comprobante_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_relacionados', to='fiscal.comprobante', verbose_name='comprobante relacionado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='inventario.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'comprobante',
                'verbose_name_plural': 'comprobantes',
                'ordering': ['-fecha_emision', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='fiscal.cuentacontable', verbose_name='cuenta padre')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='haber')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='fiscal.asientocontable', verbose_name='asiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_asiento', to='fiscal.cuentacontable', verbose_name='cuenta')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'línea de asiento',
                'verbose_name_plural': 'líneas de asiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'periodo fiscal',
                'verbose_name_plural': 'periodos fiscales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='fiscal.periodofiscal', verbose_name='periodo fiscal'),
        ),
    ]
