# Generated by Django 5.2 on 2025-06-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0002_add_fiscal_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Impuesto',
        ),
    ]
