# Generated by Django 5.2 on 2025-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo_identificacion', models.CharField(choices=[('cedula', 'Cédula'), ('ruc', 'RUC'), ('pasaporte', 'Pasaporte')], max_length=10, verbose_name='tipo de identificación')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='identificación')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, verbose_name='apellidos')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='nombre comercial')),
                ('tipo_cliente', models.CharField(choices=[('persona', 'Persona Natural'), ('empresa', 'Empresa')], default='persona', max_length=10, verbose_name='tipo de cliente')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, verbose_name='celular')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='límite de crédito')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='días de crédito')),
                ('recibir_promociones', models.BooleanField(default=True, verbose_name='recibir promociones')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='apellidos')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('celular', models.CharField(blank=True, max_length=15, verbose_name='celular')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es contacto principal')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'contacto de cliente',
                'verbose_name_plural': 'contactos de clientes',
                'ordering': ['cliente', 'nombres', 'apellidos'],
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('tipo', models.CharField(choices=[('facturacion', 'Facturación'), ('envio', 'Envío'), ('oficina', 'Oficina'), ('casa', 'Casa'), ('otro', 'Otro')], max_length=15, verbose_name='tipo')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('direccion', models.TextField(verbose_name='dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='código postal')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es dirección principal')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='longitud')),
            ],
            options={
                'verbose_name': 'dirección de cliente',
                'verbose_name_plural': 'direcciones de clientes',
                'ordering': ['cliente', 'tipo', 'nombre'],
            },
        ),
    ]
