# Generated by Django 5.2 on 2025-06-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactocliente',
            options={'ordering': ['cliente', '-es_principal', 'nombres'], 'verbose_name': 'contacto de cliente', 'verbose_name_plural': 'contactos de clientes'},
        ),
        migrations.AddField(
            model_name='contactocliente',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('comercial', 'Comercial'), ('tecnico', 'Técnico'), ('financiero', 'Financiero'), ('otro', 'Otro')], default='comercial', max_length=15, verbose_name='tipo de contacto'),
        ),
        migrations.AlterUniqueTogether(
            name='contactocliente',
            unique_together={('cliente', 'email')},
        ),
    ]
