# Generated by Django 5.2 on 2025-06-20 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('tipo', models.CharField(choices=[('ventas', 'Ventas'), ('inventario', 'Inventario'), ('clientes', 'Clientes'), ('reparaciones', 'Reparaciones'), ('contabilidad', 'Contabilidad'), ('personalizado', 'Personalizado')], max_length=15, verbose_name='tipo')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], default='pdf', max_length=5, verbose_name='formato')),
                ('consulta_sql', models.TextField(blank=True, verbose_name='consulta SQL')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='parámetros')),
                ('plantilla', models.TextField(blank=True, verbose_name='plantilla')),
                ('es_publico', models.BooleanField(default=False, verbose_name='es público')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'reporte',
                'verbose_name_plural': 'reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=10, verbose_name='frecuencia')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='día de la semana')),
                ('dia_mes', models.IntegerField(blank=True, null=True, verbose_name='día del mes')),
                ('mes', models.IntegerField(blank=True, null=True, verbose_name='mes')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='parámetros')),
                ('destinatarios', models.TextField(help_text='Correos electrónicos separados por comas', verbose_name='destinatarios')),
                ('asunto', models.CharField(max_length=200, verbose_name='asunto')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='última ejecución')),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='próxima ejecución')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='reportes.reporte', verbose_name='reporte')),
            ],
            options={
                'verbose_name': 'programación de reporte',
                'verbose_name_plural': 'programaciones de reportes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ejecución')),
                ('duracion', models.IntegerField(blank=True, null=True, verbose_name='duración (segundos)')),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('error', 'Error')], max_length=5, verbose_name='estado')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='mensaje de error')),
                ('parametros', models.JSONField(blank=True, default=dict, verbose_name='parámetros')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='archivo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='reportes.programacionreporte', verbose_name='programación')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='reportes.reporte', verbose_name='reporte')),
            ],
            options={
                'verbose_name': 'historial de reporte',
                'verbose_name_plural': 'historial de reportes',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
