# Generated by Django 5.2 on 2025-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='_subtotal',
            field=models.DecimalField(db_column='subtotal', decimal_places=2, default=0, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='_total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='_total_impuestos',
            field=models.DecimalField(db_column='total_impuestos', decimal_places=2, default=0, max_digits=10, verbose_name='total impuestos'),
        ),
    ]
