# Generated by Django 5.2 on 2025-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_add_carrito_total_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='_impuestos',
            field=models.DecimalField(db_column='impuestos', decimal_places=2, default=0, max_digits=10, verbose_name='impuestos'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='_subtotal',
            field=models.DecimalField(db_column='subtotal', decimal_places=2, default=0, max_digits=10, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='_total',
            field=models.DecimalField(db_column='total', decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        ),
    ]
