# Generated by Django 5.2 on 2025-06-18 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_add_item_carrito_total_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='fecha de reserva')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='fecha de expiración')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('item_carrito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_stock', to='ecommerce.itemcarrito', verbose_name='item de carrito')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'reserva de stock',
                'verbose_name_plural': 'reservas de stock',
                'ordering': ['-fecha_reserva'],
            },
        ),
    ]
