# Generated by Django 5.2 on 2025-05-29 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria', verbose_name='categoría padre')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio de venta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('descontinuado', 'Descontinuado')], default='activo', max_length=15, verbose_name='estado')),
                ('tipo', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=10, verbose_name='tipo')),
                ('iva', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='IVA (%)')),
                ('es_inventariable', models.BooleanField(default=True, verbose_name='es inventariable')),
                ('mostrar_en_tienda', models.BooleanField(default=True, verbose_name='mostrar en tienda')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('url_slug', models.SlugField(blank=True, max_length=255, verbose_name='URL slug')),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True, verbose_name='fecha última compra')),
                ('fecha_ultimo_movimiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha último movimiento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='categoría')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('sitio_web', models.URLField(blank=True, verbose_name='sitio web')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre de contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono de contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('dias_credito', models.PositiveIntegerField(default=0, verbose_name='días de crédito')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='límite de crédito')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('devolucion', 'Devolución'), ('traslado', 'Traslado')], max_length=15, verbose_name='tipo')),
                ('origen', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste_manual', 'Ajuste Manual'), ('devolucion_cliente', 'Devolución de Cliente'), ('devolucion_proveedor', 'Devolución a Proveedor'), ('traslado', 'Traslado entre Sucursales'), ('inicial', 'Inventario Inicial')], max_length=20, verbose_name='origen')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock anterior')),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock nuevo')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='costo unitario')),
                ('documento', models.CharField(blank=True, max_length=50, verbose_name='documento')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de referencia')),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, verbose_name='tipo de referencia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto', verbose_name='producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.proveedor', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
