# Generated by Django 5.2 on 2025-06-18 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('stock_actual', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock actual')),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='stock mínimo')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de detección')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('notificado', models.BooleanField(default=False, verbose_name='notificado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_stock', to='inventario.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'alerta de stock',
                'verbose_name_plural': 'alertas de stock',
                'ordering': ['-fecha_deteccion'],
            },
        ),
    ]
