# Generated by Django 5.2 on 2025-05-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0002_initial'),
        ('ventas', '0002_alter_detalleventa_options_alter_pago_metodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='reparaciones.reparacion', verbose_name='reparación'),
        ),
        migrations.AddField(
            model_name='venta',
            name='validez',
            field=models.PositiveIntegerField(default=15, help_text='Solo para proformas', verbose_name='validez (días)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_relacionada',
            field=models.ForeignKey(blank=True, help_text='Para proformas convertidas a facturas o viceversa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_relacionadas', to='ventas.venta', verbose_name='venta relacionada'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('factura', 'Factura'), ('proforma', 'Proforma'), ('nota_venta', 'Nota de Venta'), ('ticket', 'Ticket')], default='factura', max_length=10, verbose_name='tipo'),
        ),
    ]
