# Generated by Django 5.2 on 2025-06-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='certificado_digital',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ruta_certificado',
            field=models.CharField(blank=True, help_text='Ruta absoluta al archivo .p12 en el servidor.', max_length=255, verbose_name='ruta del certificado P12'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='url_autorizacion_produccion',
            field=models.URLField(blank=True, default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl', verbose_name='URL Autorización (Producción)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='url_autorizacion_pruebas',
            field=models.URLField(blank=True, default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl', verbose_name='URL Autorización (Pruebas)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='url_recepcion_produccion',
            field=models.URLField(blank=True, default='https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl', verbose_name='URL Recepción (Producción)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='url_recepcion_pruebas',
            field=models.URLField(blank=True, default='https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl', verbose_name='URL Recepción (Pruebas)'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ambiente_facturacion',
            field=models.CharField(choices=[('1', 'Pruebas'), ('2', 'Producción')], default='1', max_length=1, verbose_name='ambiente de facturación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='clave_certificado',
            field=models.CharField(blank=True, max_length=255, verbose_name='clave del certificado'),
        ),
    ]
