# Generated by Django 5.2 on 2025-06-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logactividad',
            name='datos_anteriores',
            field=models.JSONField(blank=True, help_text='Estado del objeto antes de la modificación, si aplica.', null=True, verbose_name='datos anteriores'),
        ),
        migrations.AddField(
            model_name='logactividad',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Información del cliente/navegador del usuario.', max_length=255, verbose_name='user agent'),
        ),
    ]
