# Generated by Django 5.2 on 2025-05-29 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('PREFIJO_FACTURA', models.CharField(default='FAC-', max_length=10, verbose_name='prefijo factura')),
                ('PREFIJO_PROFORMA', models.CharField(default='PRO-', max_length=10, verbose_name='prefijo proforma')),
                ('PREFIJO_NOTA_VENTA', models.CharField(default='NV-', max_length=10, verbose_name='prefijo nota de venta')),
                ('PREFIJO_TICKET', models.CharField(default='TIK-', max_length=10, verbose_name='prefijo ticket')),
                ('INICIO_FACTURA', models.PositiveIntegerField(default=1, verbose_name='inicio numeración factura')),
                ('INICIO_PROFORMA', models.PositiveIntegerField(default=1, verbose_name='inicio numeración proforma')),
                ('INICIO_NOTA_VENTA', models.PositiveIntegerField(default=1, verbose_name='inicio numeración nota de venta')),
                ('INICIO_TICKET', models.PositiveIntegerField(default=1, verbose_name='inicio numeración ticket')),
                ('IVA_PORCENTAJE', models.DecimalField(decimal_places=2, default=12.0, max_digits=5, verbose_name='porcentaje IVA')),
                ('NOMBRE_EMPRESA', models.CharField(default='Mi Empresa', max_length=100, verbose_name='nombre de la empresa')),
                ('RUC', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('DIRECCION', models.TextField(blank=True, verbose_name='dirección')),
                ('TELEFONO', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('EMAIL', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('SITIO_WEB', models.URLField(blank=True, verbose_name='sitio web')),
                ('AMBIENTE_FACTURACION', models.CharField(choices=[('pruebas', 'Pruebas'), ('produccion', 'Producción')], default='pruebas', max_length=10, verbose_name='ambiente de facturación')),
                ('CLAVE_CERTIFICADO', models.CharField(blank=True, max_length=100, verbose_name='clave del certificado')),
                ('RUTA_CERTIFICADO', models.CharField(blank=True, max_length=255, verbose_name='ruta del certificado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'configuración del sistema',
                'verbose_name_plural': 'configuraciones del sistema',
            },
        ),
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
