# Generated by Django 5.2 on 2025-06-09 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='porcentaje')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('es_default', models.BooleanField(default=False, verbose_name='es predeterminado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='modificado por')),
            ],
            options={
                'verbose_name': 'tipo de IVA',
                'verbose_name_plural': 'tipos de IVA',
                'ordering': ['nombre'],
            },
        ),
    ]
