# Generated by Django 5.2 on 2025-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logactividad_datos_anteriores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logactividad',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Información del cliente/navegador del usuario.', max_length=255, null=True, verbose_name='user agent'),
        ),
    ]
